version: '3.0'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.61.0/24

volumes:
  cs-ansible:
  jenkins-docker-certs:
  jenkins-data:
  gitlab-config:
  gitlab-data:
  gitlab-logs:
  postgres:
  pgadmin:

services:
  control:
    container_name: control
    image: codespaces/ansible-control:3.0.0
    ports:
      - "8000:8000"
    volumes:
      - cs-ansible:/root/workspace
    networks:
      custom:
        ipv4_address: 192.168.61.10
    dns: 8.8.8.8
    domainname: mdynamics.local
    hostname: control
    restart: always
  frontend:
    container_name: frontend
    image: codespaces/ansible-node-ubuntu:18.04
    ports:
       - "8079:8079"
    networks:
      custom:
        ipv4_address: 192.168.61.11
    dns: 8.8.8.8
    domainname: mdynamics.local
    hostname: frontend
    restart: always
  catalogue:
    container_name: catalogue
    image: codespaces/ansible-node-ubuntu:18.04
    ports:
       - "7081:80"
    networks:
      custom:
        ipv4_address: 192.168.61.12
    dns: 8.8.8.8
    domainname: mdynamics.in
    hostname: catalogue
    restart: always
  carts:
    container_name: carts
    image: codespaces/ansible-node-ubuntu:18.04
    ports:
      - "8081:80"
    networks:
      custom:
        ipv4_address: 192.168.61.13
    dns: 8.8.8.8
    domainname: mdynamics.in
    hostname: carts
    restart: always
  carts-db:
    container_name: carts-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123

  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      custom:
        ipv4_address: 192.168.61.15
    dns: 8.8.8.8
    domainname: mdynamics.in
    hostname: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on: 
      - docker

  docker:
    container_name: docker
    image: docker:dind
    ports:
      - 2376:2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      custom:
        ipv4_address: 192.168.61.16
        aliases:
          - docker
    privileged: true
    domainname: mdynamics.in
    hostname: docker
    restart: always
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
      - "8888:80"
      - "22:22"
      - "443:443"
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'https://gitlab.mdynamics.in/';"
    networks:
      custom:
        ipv4_address: 192.168.61.17
        aliases:
          - gitlab
    privileged: true
    domainname: mdynamics.in
    hostname: gitlab
    restart: always
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

  theia:
    container_name: theia
    image: theiaide/theia:next
    init: true
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=ide.mdynamics.in
      - LETSENCRYPT_HOST=ide.mdynamics.in
    networks:
      custom:
        ipv4_address: 192.168.61.20
        aliases:
          - theia
    privileged: false
    domainname: mdynamics.in
    hostname: theia
    restart: always
    volumes:
      - ./:/home/project:cached

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      custom:
        ipv4_address: 192.168.61.21
        aliases:
          - postgres
    restart: unless-stopped
    privileged: false
    domainname: mdynamics.in
    hostname: postgres
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
       custom:
        ipv4_address: 192.168.61.22
        aliases:
          - pgadmin
    restart: unless-stopped
    privileged: false
    domainname: mdynamics.in
    hostname: pgadmin

  web:
    container_name: web
    image: nginx
    environment:
      - NGINX_HOST=mdynamics.local
      - NGINX_PORT=80
    volumes:
      - ~/workspace/m-dynamics.github.io:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
       custom:
        ipv4_address: 192.168.61.23
        aliases:
          - web
    restart: unless-stopped
    privileged: false
    domainname: mdynamics.in
    hostname: web